spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
<<<<<<< HEAD
          search-locations: file:///C:\Users\FAISAL\Desktop\courses\embarkx\Microservices\ecom-microservices\additional\config-mgmt\configserver\src\main\resources\config
=======
          search-locations: classpath\config
>>>>>>> 98dd4245391fe1cff2886406a1318aadb1c311d7
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  cloud:
#    config:
#      server:
#        git:
<<<<<<< HEAD
#          uri: https://github.com/faisal-courses/app-configuration
=======
#          uri: https://github.com/abhishek0903200/app-configuration.git
>>>>>>> 98dd4245391fe1cff2886406a1318aadb1c311d7
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username: ${USER}
#    password: ${PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
#          default-label: main

server:
  port: 8888
<<<<<<< HEAD

#encrypt:
#  key: "0E329232EA6D0D73"

encrypt:
  key-store:
    location: config-server.jks
    password: mypass
    alias: config-server-key
=======
#
##encrypt:
##  key: "0E329232EA6D0D73"
#
#encrypt:
#  key-store:
#    location: config-server.jks
#    password: mypass
#    alias: config-server-key
>>>>>>> 98dd4245391fe1cff2886406a1318aadb1c311d7
