spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
<<<<<<< HEAD
    virtual-host: ${RABBITMQ_VHOST:guest}
=======
    virtual-host: ${RABBITMQ_VHOST:/}
>>>>>>> 98dd4245391fe1cff2886406a1318aadb1c311d7
    connection-timeout: 30000
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
<<<<<<< HEAD
        include: "*"
=======
        include: "*"
>>>>>>> 98dd4245391fe1cff2886406a1318aadb1c311d7
